- name: Get certificate
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Generate join command for nodes
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Join master nodes to the cluster
  shell: "{{ join_command_raw.stdout }} --control-plane --certificate-key {{ cert.stdout.splitlines()[-1] }}"
  when: 
    - "'k8s-master' in group_names"
    - inventory_hostname != groups['k8s-master'][0]

- name: Join worker nodes to the cluster
  shell: "{{ join_command_raw.stdout }}"
  when: 
    - "'k8s-worker' in group_names"