---
- name: Copy kubeadm config
  ansible.builtin.copy:
    src: kubeadm.yml
    dest: /etc
    mode: '0644'

- name: Kubeadm init
  ansible.builtin.command: kubeadm init --config /etc/kubeadm.yml

- name: Setup kubeconfig for debian user
  ansible.builtin.command: "{{ item }}"
  with_items:
    - mkdir -p /home/debian/.kube
    - cp -i /etc/kubernetes/admin.conf /home/debian/.kube/config
    - chown debian:debian /home/debian/.kube/config

- name: Install calico pod network
  become: false
  ansible.builtin.command: kubectl create -f https://calico-v3-25.netlify.app/archive/v3.25/manifests/calico.yaml

- name: Symlink cni dir for debian
  ansible.builtin.file:
    src: /opt/cni/bin
    dest: /usr/lib/cni
    state: link
