---
- name: Install HAProxy
  ansible.builtin.apt:
    update_cache: true
    name: haproxy=2.6.12-1+deb12u3
  become: true

- name: Copy config file
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  become: true
