# - name: Bastion
#   hosts: bastion
#   roles: 
#     - haproxy

# - name: Vault
#   hosts: vault
#   roles:
#     - vault

# - name: GitLab
#   hosts: gitlab
#   roles:
#     - gitlab-init
#     - gitlub-runners

- name: Set up common for cluster
  hosts:
    - k8s-master
    - k8s-worker

- name: Initialize first master node
  hosts: 
    - k8s-master
  roles:
    - role: k8s-init
      when: inventory_hostname == groups['k8s-master'][0]

# - name: Joining a k8s-worker to a cluster
#   hosts: 
#     - k8s-worker
#   roles: 
#     - role: k8s-master-join
#       when: inventory_hostname != groups['k8s-master'][0]

# - name: Joining a k8s-worker to a cluster
#   hosts: 
#     - k8s-worker
#   roles: 
#     - k8s-worker-join
