plugin: cloud.terraform.terraform_state

backend_type: s3
backend_config:
  region: ru-central1
  bucket: "{{ lookup('env', 'BUCKET') }}"
  key: "terraform/{{ lookup('env', 'ENV') }}/terraform.tfstate"
  skip_region_validation: true
  scip_credentials_validation: true

provider_mapping:
  - provider_name: registry.terraform.io/yandex-cloud/yandex
    types:
      - yandex_compute_instance

hostnames: 
  - name


