---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - containerd

- name: Copy containerd config
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd

- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/  /
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Change sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    line: 'net.ipv4.ip_forward=1'
    state: present

- name: Ip_Forward on
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
