---
name: Ansible Playbook

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    
jobs:
  check-dev:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup Ansible
        run: |
          python3 -m pip install ansible

      - name: Run Playbook
        working-directory: ./ansible/
        run: |
          ansible-playbook -i ./inventories/${{ inputs.environment }}/inventory playbook.yml