---
name: Ansible

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    
jobs:
  check-dev:
    runs-on: ubuntu-latest
    container:
      image: python:3.14.0rc3-alpine3.22
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup Ansible
        run: |
          python3 -m pip install ansible

      - name: Auto playbook
        working-directory: ./ansible/
        run: |
          ansible-playbook -i ./inventories/${{ env.DIR }}/inventory playbook.yml