---
name: Ansible auto playbooks

on:
  workflow_run:
    workflows: [terraform]
    types:
      - completed
      
  pull_request:
    types:
      - closed
    branches: 
      - main
      - dev
    
jobs:
  auto:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install ansible

      - name: Auto playbook
        working-directory: ./ansible/
        run: |
          ansible-playbook -i ./inventories/${{ github.ref_name }}/inventory playbook.yml