---
name: Ansible Playbook

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      CLOUD:
        required: true
      FOLDER:
        required: true
      DOMAIN:
        required: true
      PUBLIC_SSH_KEY:
        required: true
      BUCKET:
        required: true
      ACCESS_KEY:
        required: true
      SECRET_KEY:
        required: true
    
jobs:
  playbook:
    name: Playbook
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_token: ${{ secrets.TOKEN }}
      TF_VAR_cloud: ${{ secrets.CLOUD }}
      TF_VAR_folder: ${{ secrets.FOLDER }}
      TF_VAR_domain: ${{ secrets.DOMAIN }}
      TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
      BUCKET: ${{ secrets.BUCKET }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Setup Ansible
        run: |
          python3 -m pip install ansible

      - name: Install Ansible collection
        run: |
          ansible-galaxy collection install cloud.terraform

      - name: Terraform Init
        working-directory: ./terraform/
        run: |
          terraform init -input=false \
            -backend-config="key=terraform/${{ inputs.environment }}/terraform.tfstate" \
            -backend-config="bucket=${{ secrets.BUCKET }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SECRET_KEY }}"

      - name: DEBUG terraform
        working-directory: ./terraform/.terraform
        run: |
          ls -a

      - name: DEBUG ansible
        working-directory: ./terraform/.terraform
        run: |
          cat terraform.tfstate

      - name: Check generate Ansible inventory
        working-directory: ./ansible/
        run: |
          ansible-inventory -i inventory.yml --graph 

      - name: Run Playbook
        working-directory: ./ansible/
        run: |
          ansible-playbook -i inventory.yml main_ci.yml