---
name: Ansible Playbook

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      CLOUD:
        required: true
      FOLDER:
        required: true
      DOMAIN:
        required: true
      PUBLIC_SSH_KEY:
        required: true
      BUCKET:
        required: true
      ACCESS_KEY:
        required: true
      SECRET_KEY:
        required: true
    
jobs:
  playbook:
    name: Playbook
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_token: ${{ secrets.TOKEN }}
      TF_VAR_cloud: ${{ secrets.CLOUD }}
      TF_VAR_folder: ${{ secrets.FOLDER }}
      TF_VAR_domain: ${{ secrets.DOMAIN }}
      TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
      BUCKET: ${{ secrets.BUCKET }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ENV: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Setup Ansible
        run: |
          python3 -m pip install ansible

      - name: Setup lib
        run: |
          pip install requests

      - name: Run Playbook
        working-directory: ./ansible/
        run: |
          ansible-playbook -i yandex_ec2.yml main_ci.yml