---
name: Ansible Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v25.9.2
        with:
          working_directory: ./ansible/

