---
name: Terraform Auto Apply

on:
  pull_request:
    types:
      - closed
    branches: 
      - main
      - dev

env:
  TF_VAR_token: ${{ secrets.TOKEN }}
  TF_VAR_cloud: ${{ secrets.CLOUD }}
  TF_VAR_folder: ${{ secrets.FOLDER }}
  TF_VAR_domain: ${{ secrets.DOMAIN }}
  TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}

jobs:
  auto:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [simple_dev]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Trraform Init
        working-directory: ./terraform/${{ github.ref_name }}
        run: |
          terraform init -input=false \
            -backend-config="key=terraform/${{ github.ref_name }}/terraform.tfstate" \
            -backend-config="bucket=${{ secrets.BUCKET }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SECRET_KEY }}"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./terraform/${{ github.ref_name }}
        run: |
          terraform plan -input=false -compact-warnings -out=plan_${{ github.ref_name }}.file
      
      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: plan_${{ github.ref_name }}.file
          path: terraform/${{ github.ref_name }}/plan_${{ github.ref_name }}.file
          retention-days: 7

      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        working-directory: ./terraform/${{ github.ref_name }}
        run: |
          terraform apply plan_${{ github.ref_name }}.file \
            -var="key=terraform/${{ github.ref_name }}/terraform.tfstate" \
            -var="bucket=${{ secrets.BUCKET }}" \
            -var="access_key=${{ secrets.ACCESS_KEY }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}
