---
name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      # - name: Terraform Init
      #   working-directory: ./terraform/
      #   run: |
      #     terraform init -input=false \
      #       -backend-config="key=terraform/${{ inputs.environment }}/terraform.tfstate" \
      #       -backend-config="bucket=${{ secrets.BUCKET }}" \
      #       -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
      #       -backend-config="secret_key=${{ secrets.SECRET_KEY }}"
            
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: plan.file
          path: ./terraform/

      - name: Terraform Apply
        working-directory: ./terraform/
        run: |
          terraform apply -input=false plan.file